/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PianoPack;

import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Joni
 */
public class PianoGUI extends javax.swing.JFrame {

    /**
     * Creates new form PianoGUI
     */
    public PianoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNote = new javax.swing.JButton();
        cNote = new javax.swing.JButton();
        dNote = new javax.swing.JButton();
        fNote = new javax.swing.JButton();
        gNote = new javax.swing.JButton();
        aNote = new javax.swing.JButton();
        bNote = new javax.swing.JButton();
        gSharpNote = new javax.swing.JButton();
        cSharpNote = new javax.swing.JButton();
        dSharpNote = new javax.swing.JButton();
        fSharpNote = new javax.swing.JButton();
        bbNote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yksinkertainen Piano");
        setResizable(false);

        eNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        eNote.setText("E");
        eNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        eNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNoteActionPerformed(evt);
            }
        });

        cNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        cNote.setText("C");
        cNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNoteActionPerformed(evt);
            }
        });

        dNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        dNote.setText("D");
        dNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNoteActionPerformed(evt);
            }
        });

        fNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        fNote.setText("F");
        fNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNoteActionPerformed(evt);
            }
        });

        gNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        gNote.setText("G");
        gNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gNoteActionPerformed(evt);
            }
        });

        aNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        aNote.setText("A");
        aNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNoteActionPerformed(evt);
            }
        });

        bNote.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        bNote.setText("B");
        bNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoteActionPerformed(evt);
            }
        });

        gSharpNote.setBackground(new java.awt.Color(0, 0, 0));
        gSharpNote.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        gSharpNote.setForeground(new java.awt.Color(255, 255, 255));
        gSharpNote.setText("G#");
        gSharpNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gSharpNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSharpNoteActionPerformed(evt);
            }
        });

        cSharpNote.setBackground(new java.awt.Color(0, 0, 0));
        cSharpNote.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        cSharpNote.setForeground(new java.awt.Color(255, 255, 255));
        cSharpNote.setText("C#");
        cSharpNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cSharpNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSharpNoteActionPerformed(evt);
            }
        });

        dSharpNote.setBackground(new java.awt.Color(0, 0, 0));
        dSharpNote.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        dSharpNote.setForeground(new java.awt.Color(255, 255, 255));
        dSharpNote.setText("D#");
        dSharpNote.setToolTipText("");
        dSharpNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dSharpNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSharpNoteActionPerformed(evt);
            }
        });

        fSharpNote.setBackground(new java.awt.Color(0, 0, 0));
        fSharpNote.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        fSharpNote.setForeground(new java.awt.Color(255, 255, 255));
        fSharpNote.setText("F#");
        fSharpNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fSharpNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSharpNoteActionPerformed(evt);
            }
        });

        bbNote.setBackground(new java.awt.Color(0, 0, 0));
        bbNote.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bbNote.setForeground(new java.awt.Color(255, 255, 255));
        bbNote.setText("Bb");
        bbNote.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bbNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cSharpNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dSharpNote)
                        .addGap(67, 67, 67)
                        .addComponent(fSharpNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gSharpNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bbNote))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSharpNote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSharpNote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dSharpNote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gSharpNote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/e.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }
    }//GEN-LAST:event_eNoteActionPerformed

    private void cNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/c.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }
    }//GEN-LAST:event_cNoteActionPerformed

    private void dNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/d.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }
    }//GEN-LAST:event_dNoteActionPerformed

    private void fNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/f.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }
    }//GEN-LAST:event_fNoteActionPerformed

    private void gNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/g.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }
    }//GEN-LAST:event_gNoteActionPerformed

    private void aNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/a.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_aNoteActionPerformed

    private void bNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/b.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_bNoteActionPerformed

    private void cSharpNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSharpNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/c#.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_cSharpNoteActionPerformed

    private void dSharpNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSharpNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/d#.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_dSharpNoteActionPerformed

    private void fSharpNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSharpNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/f#.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_fSharpNoteActionPerformed

    private void gSharpNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSharpNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/g#.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_gSharpNoteActionPerformed

    private void bbNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbNoteActionPerformed
        InputStream audio;
        
        try {
            audio = getClass().getResourceAsStream("/snd/bb.wav");
            AudioStream music = new AudioStream(audio);
            AudioPlayer.player.start(music);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }    
    }//GEN-LAST:event_bbNoteActionPerformed

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aNote;
    private javax.swing.JButton bNote;
    private javax.swing.JButton bbNote;
    private javax.swing.JButton cNote;
    private javax.swing.JButton cSharpNote;
    private javax.swing.JButton dNote;
    private javax.swing.JButton dSharpNote;
    private javax.swing.JButton eNote;
    private javax.swing.JButton fNote;
    private javax.swing.JButton fSharpNote;
    private javax.swing.JButton gNote;
    private javax.swing.JButton gSharpNote;
    // End of variables declaration//GEN-END:variables
}
